#!/bin/bash
# Preview 环境数据库配置脚本
# 请在 Vercel Dashboard 中手动执行以下配置

echo "=== Preview 环境数据库配置 ==="
echo ""
echo "由于 Supabase 分支需要手动创建，请按以下步骤操作："
echo ""
echo "步骤 1: 创建 Supabase Preview 分支"
echo "  1. 登录 https://supabase.com/dashboard"
echo "  2. 进入项目: xsdgqzuzlqthznygmjev"
echo "  3. 点击左侧 'Branches'"
echo "  4. 点击 'New Branch'"
echo "  5. 分支名: preview"
echo "  6. 等待分支创建完成"
echo ""
echo "步骤 2: 获取 Preview 分支连接字符串"
echo "  1. 进入 preview 分支"
echo "  2. 点击 'Connect' → 'Connection String'"
echo "  3. 复制 Transaction 连接字符串"
echo ""
echo "步骤 3: 在 Vercel Dashboard 配置环境变量"
echo "  1. 登录 https://vercel.com/dashboard"
echo "  2. 进入项目: wig-management"
echo "  3. 点击 'Settings' → 'Environment Variables'"
echo "  4. 添加以下变量:"
echo ""
echo "     变量名: DATABASE_URL"
echo "     值: [从 Supabase 复制的连接字符串]"
echo "     环境: Preview (勾选)"
echo ""
echo "     变量名: DIRECT_URL"
echo "     值: [从 Supabase 复制的连接字符串，去掉 pgbouncer]"
echo "     环境: Preview (勾选)"
echo ""
echo "步骤 4: 重新部署 Preview"
echo "  1. 在 Vercel Dashboard 点击 'Deployments'"
echo "  2. 找到最新的 Preview 部署"
echo "  3. 点击 'Redeploy'"
echo ""
echo "=== 验证隔离 ==="
echo "部署完成后，访问 Preview 链接，确认数据与 Production 不同"
